apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-secret-llrb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-secret-llrb
    app.kubernetes.io/part-of: hello-secret
  name: hello-secret-llrb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: hello-secret-llrb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hello-secret-llrb
    spec:
      containers:
      - env:
        - name: SECRET
          value: RHTAP
        - name: VALUE
          value: test
        image: quay.io/redhat-user-workloads/ergonzale-tenant/hello-secret/hello-secret-llrb@sha256:ac002416cf3891f039f646b09912d0412406bc57eca318af80707f689ed850d3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
