apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hello-secret-llrb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ergonzale-tenant/hello-secret/hello-secret-llrb@sha256:c4072b435f440b60f12c0ef582db28e9972cff7964cbe738745106763efbf5d8
        name: container-image
        resources: {}
status: {}
