apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-secret-llrb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-secret-llrb
    app.kubernetes.io/part-of: hello-secret
  name: hello-secret-llrb37nv
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: hello-secret-llrb
    weight: 100
status: {}
